### PR TITLE
fix CMakeLists.txt for Ecc target and case-sensitivity in includes

### PR DESCRIPTION
**Pull request by LeonardKoenig**
The file's called StdH.h not stdh.h

### CODE REVIEW

**Comment by LeonardKoenig** [comment]
Now one can even run `Ecc Sources/Engine/Classes/BaseEvents.es` and it works :-)
Still having many issues, especially with types yet.

**Comment by Ragora** [comment]
I figured there was probably some includes floating around I forgot to correct to case sensitivity. Will merge and see how it affects my build here, though Ryan C Gordon probably already has us beat on this -- unless he isn't using CMake for some reason.

**Comment by LeonardKoenig** [comment]
Yep, probably -- but it's fun anyway :-)

There are possibly some more changes lined up that I currently prepare in
my fork in the devel branch. I got it to compile 3 projects on Win using
the CMake projects only it won't yet link with the EngineD.lib.

On Linux I yet was able to have a nice and stable Ecc (it's more stable
than theirs :D )

Will see how far one can get.

**Comment by Ragora** [comment]
I'll look into adding an engine pre-build task to invoke Ecc across all .es files in Classes/ and ditto for any other components that have es files to compile like that. CMake makes that relatively easy to do. From there we'll probably just have to build Engine first so that those files are built and then everything else after.

**Comment by Ragora** [comment]
Just added it as a post-build for Ecc to take care of everything in one go, though Ecc is broken in that it fails on empty files. Will have to work with that in some way.

**Comment by LeonardKoenig** [comment]
Yep, I've merged your work into my current [devel branch](https://github.com/LeonardKoenig/Serious-Engine/tree/devel) and played around with it more.
I've moved the POST_BUILD step to a virtual target as otherwise if the Ecc fails to compile some .es files, the Ecc binary is removed by CMake as it is considered to not have been built correctly.

Also I added a rule to compile Ecc itself without relying on the (generated) Parser.h and Parser.cpp files and also added a fix(?) to the Parser.y file (see [Croteam-official Serious-Engine #17](https://github.com/Croteam-official/Serious-Engine/issues/17)).

This lets me compile Ecc but it won't compile for example Player.es:
```
/mnt/sdata/Git/Serious-Engine/Sources/EntitiesMP/Player.es(6423): Error: memory exhausted
```

I'm not sure whether it's my 'fix' for the `Player.y` file or just that this the max default depth of Yacc is not enough as I've not really played with it before...

Do you have any idea why the es-compilation fails?

**Comment by Ragora** [comment]
I'll have to try building it myself and see what happens.

**Comment by LeonardKoenig** [comment]
Yep, 32GB here either but there's an artificial limit so it won't be exceeded. Also the problem somehow seems to be Linux only (or resulting from the CMakeLists.txt, which I doubt) as it works using their Ecc.vcxproj

Again did some work on CMake in devel, but didn't come to cleaning up, rebasing, merging etc. yet.

 - I moved the es-compilation to each target where needed
 - added EntitiesMP target
 - used FindBISON/FindFLEX modules for compiling the Parser structures
 - fixed an issue with Ecc as it generates a `#define` macro with the path to the source it called on.  
Before we were using absolute paths and on Windows we thus would generate ':' in the defines where not allowed.  
Using relative paths fixes this.

I see to cleaning them up soon so I can make a pull request.

**Pull request merged**
